description = "Генерирует подробный отчет о проделанной работе в local_reports/."
prompt = """

{{args}}
Ваша задача - сформировать отчет на английском языке о проделанной работе по разработке. Вы будете использовать структурированный подход к документированию изменений и соответствующему хранению отчёта.

В задачу входит:
1. Определение всех файлов, которые были изменены в ходе выполнения задачи.
2. Создание подробного отчёта на русском языке с описанием проделанной работы.
3. Сохранение отчёта в каталоге local_reports/.
4. Использование формата сообщения о коммите в стиле Git для имени файла на английском языке.
5. Включите список всех измененных файлов в начало отчета.

При выполнении вашей задачи:

1. Начните с анализа проделанной работы, чтобы идентифицировать все измененные файлы

2. Структурируйте свой отчет, включив в него следующие разделы:
   - Список измененных файлов (в самом начале)
   - Краткое описание проделанной работы
   - Подробное описание изменений
   - Технические замечания по внедрению
   - Предпринятые шаги по проверке
   - Оставшиеся нерешенные задачи (не обязательный пункт)
   - Рекомендации по решению оставшихся задач (не обязательный пункт)

3. Требования к именованию файлов:
   - Сохраните отчет в каталоге local_reports/
   - Следуйте стилю сообщения о фиксации Git (например, feat_add_report_functionality.md)
   - Имя файла должно быть кратким и точно отражать проделанную работу
   - Используйте расширение .md для формата markdown

Следуйте этим рекомендациям, чтобы составить профессиональный и подробный отчёт о проделанной работе, соответствующий требованиям к организации файлов.

"""