description = "Обновляет тесты в папке tests/ и документацию в папке docs/."
prompt = """

{{args}}
Проверьте пожалуйста tests/ не нужно ли обновить существующие. В начале прочитайте docs/DEVELOPMENT.md . Затем еще проверьте пожалуйста docs/ не нужно ли обновить соответстующие разделы. Перед внесением изменений в документацию пожалуйста, проверьте какие стр уже сущетсвуют.

"""