description = "Обновляет документацию в папке docs/."
prompt = """

{{args}}
Проверьте пожалуйста docs/ не нужно ли обновить соответстующие разделы. Перед внесением изменений в документацию пожалуйста, проверьте какие стр уже сущетсвуют.

"""