description = "Генерирует подробный отчет о проделанной работе в папке local_reports/."
prompt = """

{{args}}
Пожалуйста сгенерируйте подробный отчет о проделанной работе на русском языке. Отчет должен быть сохранен в уже существующей папке `local_reports/`. Имя файла отчета должно быть на английском языке, в стиле сообщения коммита Git (например, `feat_add_report_folder.md`), максимально сжатым и отражающим суть изменений. В начале отчета перечислите все файлы, которые были изменены в ходе выполнения задачи.

"""