description = "Выполняет задания из project_goals/task.md"
prompt = """

{{args}}
Пожалуйста, прочитайте temp/task.md, он содержит задание с подробными инструкциями, которые нужно последовательно выполнить.

"""